name: Quantum_Computing_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - pillow
  - ipywidgets
  - ipympl
  - pythreejs
  - notebook
  - jupyterlab
  - pyscf 
  - pip
  - pip:
      - nb_mypy
      - plotly
      - jupyterlab_mathjax2
      - widgetsnbextension
      - qiskit
      - qiskit-aer
      - qiskit-nature
      - qiskit-ibm-runtime
      - qiskit-serverless
      - qiskit-ibm-catalog
      - pylatexenc
      - qiskit_algorithms

